spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# セッション有効期限（秒）: 30分 = 1800秒
server.servlet.session.timeout=1800