spring.application.name=demo

mybatis.configuration.map-underscore-to-camel-case=true

spring.datasource.url=jdbc:postgresql://localhost:5432/Stationary
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.type-aliases-package=com.example.fullness.stationary.entity

# セッション有効期限（秒）: 30分 = 1800秒
server.servlet.session.timeout=1800